version: '2'
services:
  backoffice-service:
    build: .
    container_name: backoffice-service
    ports:
      - "9090:8080"
      - "19090:8787"
    depends_on:
      - backofficedb

  backofficedb:
    image: postgres
    container_name: backofficedb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
